<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
<xacro:include filename="$(find fishbot_description)/urdf/fishbot/common_inertia.xacro" />
<!--声明base模块-->
<xacro:macro name="base_xacro" params="length radius">
    <link name="base_link">
    <!--机器人的身体部分-->
    <visual>
        <!--沿自己几何中心的偏移和旋转量-->
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <!--机器人身体的几何形状-->
        <geometry>
            <!--圆柱体-->
            <cylinder length="${length}" radius="${radius}"/>
            <!--<box size="0.5 0.3 0.1"/>-->

        </geometry>
        <!--机器人的材质-->
        <material name="white">
            <color rgba="1.0 1.0 1.0 0.5"/>
        </material>
    </visual>

    <collision>
        <!--沿自己几何中心的偏移和旋转量-->
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <!--机器人身体的几何形状-->
        <geometry>
            <!--圆柱体-->
            <cylinder length="${length}" radius="${radius}"/>
            <!--<box size="0.5 0.3 0.1"/>-->
        </geometry>
        <!--机器人的材质-->
        <material name="white">
            <color rgba="1.0 1.0 1.0 0.5"/>
        </material>
    </collision>
    <xacro:cylinder_inertia m="1.0" r="${radius}" h="${length}" />
</link>

<link name="base_footprint">
    <!--机器人的虚拟部件-->
</link>

 <joint name="base_joint" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link"/>
        <!--子部件相对于父部件的平移和旋转-->
        <origin xyz="0 0 ${length/2.0+0.032-0.001}" rpy="0 0 0 "/>
    </joint>
</xacro:macro>
</robot>